add gdb dap configurations

diff --git a/RUN b/RUN
--- a/RUN
+++ b/RUN
@@ -84,8 +84,8 @@ for font in "${jetbrains_fonts[@]}"; do
     font_ttf=$(basename "$font")
     curl -fL "https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/$font" \
         -o $FONT_PATH/$font_ttf || {
-            error "Failed to install $font_ttf"
-            exit 1
+        error "Failed to install $font_ttf"
+        exit 1
     }
 done
 
@@ -107,7 +107,7 @@ success "Renaming complete!"
 
 section "Dotfiles Installation"
 status "Downloading and running install script..."
-curl -fsSL "https://raw.githubusercontent.com/ridwanalmahmud/.dotfiles/refs/heads/master/scripts/install" | sh || {
+curl -fsSL "https://raw.githubusercontent.com/ridwanalmahmud/.dotfiles/refs/heads/master/scripts/install.sh" | sh || {
     error "Failed to run dotfiles install script"
     exit 1
 }
@@ -127,7 +127,7 @@ sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/too
 }
 
 status "Configuring ZSH..."
-echo "" > "$HOME/.zshrc"
+echo "" >"$HOME/.zshrc"
 git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions || {
     error "Failed to clone zsh-autosuggestions"
     exit 1
@@ -141,13 +141,13 @@ git clone https://github.com/ridwanalmahmud/.dotfiles.git || {
 }
 
 status "Creating symlinks..."
-"$HOME/.dotfiles/scripts/symlinks" --overwrite || {
+"$HOME/.dotfiles/scripts/symlinks.sh" --overwrite || {
     error "Failed to create symlinks"
     exit 1
 }
 
 status "Running build script..."
-"$HOME/.dotfiles/scripts/build" || {
+"$HOME/.dotfiles/scripts/build.sh" || {
     error "Build script failed"
     exit 1
 }
@@ -201,7 +201,7 @@ EOF
 
 # Ensure ssh-agent is running and configured in shell startup
 status "Configuring SSH agent persistence..."
-cat >> "$HOME/.zshrc" <<EOL
+cat >>"$HOME/.zshrc" <<EOL
 
 # SSH Agent Configuration
 if [ -z "\$SSH_AUTH_SOCK" ] && [ -f "\$HOME/.ssh/${KEY_NAME}" ]; then
@@ -219,4 +219,4 @@ echo "1. Add your SSH key to GitHub:"
 echo "   cat ~/.ssh/${KEY_NAME}.pub"
 echo "2. Restart your terminal to enjoy your new environment!"
 
-"$HOME/.dotfiles/scripts/barca"
+"$HOME/.dotfiles/scripts/dashboard.sh"
