monaspace fonts

diff --git a/scripts/RUN b/scripts/RUN
--- a/scripts/RUN
+++ b/scripts/RUN
@@ -6,37 +6,48 @@ YELLOW='\033[1;33m'
 BLUE='\033[0;34m'
 NC='\033[0m'
 
+set -e
+
 section() {
     echo -e "\n${BLUE}===${NC} ${GREEN}$1${NC} ${BLUE}===${NC}"
 }
 
 status() {
-    echo -e "${YELLOW}➔${NC} $1"
+    echo -e "${YELLOW}➔ $1${NC}"
 }
 
 success() {
-    echo -e "${GREEN}✓${NC} $1"
+    echo -e "${GREEN}✓ $1${NC}"
 }
 
 error() {
-    echo -e "${RED}✗${NC} $1" >&2
+    echo -e "${RED}✗ $1${NC}" >&2
 }
 
-section "Development Environment Setup"
-echo -e "${YELLOW}Arguments needed:${NC}"
-echo "<email> <keyname> <passphrase>"
-echo -e "\n${YELLOW}Warning!${NC} Make sure the arguments are provided properly.\n"
-echo "Setup will start in a moment"
-sleep 1
+show_help() {
+    echo -e "${YELLOW}Usage:${NC}"
+    echo -e "$0 --help"
+    echo -e "$0 <email> <keyname> <passphrase>"
+    echo -e "\n${YELLOW}Warning!${NC} Make sure the arguments are provided properly.\n"
+}
+
+if [[ "$1" == "--help" ]]; then
+    show_help
+    exit 0
+fi
 
 if [ $# -ne 3 ]; then
     error "Error: All 3 arguments need to be provided"
+    show_help
     exit 1
 fi
 
 EMAIL=$1
 KEY_NAME="$2"
 PASSPHRASE="$3"
+
+section "Development Environment Setup"
+echo ""
 
 section "Setup Nix & Dotfiles"
 status "Installing nix..."
@@ -89,6 +100,12 @@ status "Configuring ZSH..."
 echo "" >"$HOME/.zshrc"
 git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions || {
     error "Failed to clone zsh-autosuggestions"
+    exit 1
+}
+
+status "Installing fonts..."
+"$HOME/.dotfiles/fonts/fonts.sh" || {
+    error "Failed to install fonts"
     exit 1
 }
 
